version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3457:3000"
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - "3456:3456"
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./database:/app/database
      - ./.env:/app/.env:ro
    environment:
      - TZ=${TZ:-UTC}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge