version: '3.8'

services:
  client:
    image: ontrak-client:beta2
    container_name: ontrak-client
    ports:
      - "3457:3000"  # Frontend port
    volumes:
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - PUID=1035
      - PGID=100
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://192.168.31.24:3456
    networks:
      - ontrak_default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
  server:
    image: ontrak-server:beta1
    container_name: ontrak-server
    user: "node"
    ports:
      - "3456:3456"  # Backend port
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./database:/app/database
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1035
      - PGID=100
      - NODE_ENV=production
      - CLIENT_URL=http://192.168.31.24:3457
      - BACKEND_URL=http://192.168.31.24:3456
      - PORT=3456
    networks:
      - ontrak_default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ontrak_default:
    name: ontrak_default
    driver: bridge