version: '3.8'

services:
  ontrak:
    image: ontrak:beta1
    container_name: ontrak
    ports:
      - "3456:3456"  # Map host port 3456 to container port 3456
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./database:/app/database
      - ./.env:/app/.env:ro
    environment:
      - TZ=
      - PUID=
      - PGID=
    networks:
      - cinelink_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cinelink_default:
    external: true